import type { Metadata } from 'next';
import '../globals.css';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
    title: 'Sign in',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>{children}</>;
}
