import type { Metadata } from 'next';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import React from 'react';
import { ToastContainer, Bounce } from 'react-toastify';

export const metadata: Metadata = {
    title: 'App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body suppressHydrationWarning className={`w-screen h-screen flex relative justify-center items-center`}>
                {children}
                <ToastContainer
                    position="top-center"
                    autoClose={3000}
                    hideProgressBar={false}
                    closeOnClick
                    theme="dark"
                    transition={Bounce}
                    className={'text-sm'}
                />
            </body>
        </html>
    );
}
